name: Testes de CI para C# Utilities Library

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.x']

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restaurar Dependências
        run: dotnet restore
        working-directory: Utilities

      - name: Construir Solução
        run: dotnet build --configuration Release --no-restore
        working-directory: Utilities

      - name: Rodar Testes
        run: dotnet test --configuration Release --no-build --verbosity normal
        working-directory: Utilities